### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by civilizeddev** [getlago/lago-nodejs-client#47]
How about using TypeScript to write source code?

I think there is no reason not to use TypeScript in this era.

Type definitions can be generated without much effort using [json2ts](http://json2ts.com/).

Below is the result of generating type definitions from [json example in the lago api reference](https://doc.getlago.com/docs/api/customer_usage/customer-usage-object)

```
export interface Charge {
  lago_id: string
  charge_model: string
}

export interface Charge {
  lago_id: string
  charge_model: string
}

export interface BillableMetric {
  lago_id: string
  name: string
  code: string
  aggregation_type: string
}

export interface ChargesUsage {
  units: string
  amount_cents: number
  amount_currency: string
  charge: Charge
  billable_metric: BillableMetric
  groups: Record<string, any>
}

export interface CustomerUsage {
  from_datetime: Date
  to_datetime: Date
  issuing_date: string
  amount_cents: number
  amount_currency: string
  total_amount_cents: number
  total_amount_currency: string
  vat_amount_cents: number
  vat_amount_currency: string
  from_date: string
  to_date: string
  charges_usage: ChargesUsage[]
}

export interface CustomerUsageResult {
  customer_usage: CustomerUsage
}
```

**Comment by arjunyel** [comment]
@civilizeddev Im currently rewriting the SDK in Typescript for my own project, I'll ping you when the PR is ready :)

**Comment by arjunyel** [comment]
@civilizeddev https://github.com/getlago/lago-nodejs-client/pull/50

**Comment by arjunyel** [comment]
@civilizeddev Hi friend, follow this new repo https://github.com/getlago/lago-javascript-client

**Comment by arjunyel** [comment]
Released on npm https://www.npmjs.com/package/lago-javascript-client
